version: '2'

services:
    db:
        image: mysql
        platform: linux/amd64
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
        #restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
    php:
        build: php7-fpm
        platform: linux/amd64
        environment:
            APP_ENV: dev
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony:cached
            - ${SYMFONY_APP_PATH}/var:/var/www/symfony/var:cached
            - ./logs/symfony:/var/www/symfony/app/logs:cached
    nginx:
        build: nginx
        platform: linux/amd64
        ports:
            - 80:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx:cached
              #elk:
              #    image: willdurand/elk
              #    ports:
              #        - 81:80
              #    volumes:
              #        - ./elk/logstash:/etc/logstash:delegated
              #        - ./elk/logstash/patterns:/opt/logstash/patterns:delegated
              #    volumes_from:
              #        - php
              #        - nginx
